import { Product, Shop } from '@/types';

export const mockShops: Shop[] = [
  {
    id: 'shop1',
    name: 'Camera Rentals Bengaluru',
    email: 'contact@camerarentalsblr.in',
    phone: '+91-9876543210',
    city: 'Bengaluru',
    address: '123 MG Road, Bengaluru',
    rating: 4.8,
    totalRatings: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop2',
    name: 'Mumbai Camera Hub',
    email: 'info@mumbaicamerahub.com',
    phone: '+91-9876543211',
    city: 'Mumbai',
    address: '456 Bandra West, Mumbai',
    rating: 4.6,
    totalRatings: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop3',
    name: 'Delhi Pro Cameras',
    email: 'hello@delhiprocameras.in',
    phone: '+91-9876543212',
    city: 'Delhi',
    address: '789 Connaught Place, Delhi',
    rating: 4.7,
    totalRatings: 110,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop4',
    name: 'Chennai Lens & Gear',
    email: 'rentals@chennailensgear.com',
    phone: '+91-9876543213',
    city: 'Chennai',
    address: '321 T Nagar, Chennai',
    rating: 4.5,
    totalRatings: 78,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Using actual camera/equipment images from Unsplash
export const mockProducts: Product[] = [
  {
    id: 'prod1',
    shopId: 'shop1',
    title: 'Canon EOS R6 + 24-70mm',
    description: 'Professional mirrorless camera with RF 24-70mm f/2.8 L lens. Perfect for weddings, events, and commercial photography.',
    category: 'Cameras',
    pricePerDay: 3500,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'mirrorless', 'full-frame', 'professional', 'wedding'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod2',
    shopId: 'shop2',
    title: 'Sony A7 IV + 50mm',
    description: 'Latest Sony full-frame mirrorless with 50mm f/1.8 prime lens. Excellent for portraits and low-light photography.',
    category: 'Cameras',
    pricePerDay: 3200,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['sony', 'mirrorless', 'full-frame', 'portrait', 'low-light'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod3',
    shopId: 'shop3',
    title: 'Nikon Z6 II + 24-70',
    description: 'Professional Nikon mirrorless camera with Z 24-70mm f/4 lens. Great for video and photography.',
    category: 'Cameras',
    pricePerDay: 3000,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['nikon', 'mirrorless', 'full-frame', 'video', 'hybrid'],
    available: true,
    instantAvailability: false,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod4',
    shopId: 'shop4',
    title: 'Fujifilm X-T4 + 18-55',
    description: 'Compact APS-C mirrorless camera with kit lens. Perfect for travel and street photography.',
    category: 'Cameras',
    pricePerDay: 1800,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['fujifilm', 'aps-c', 'travel', 'street', 'compact'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod5',
    shopId: 'shop1',
    title: 'Godox AD200 Pro Flash',
    description: 'Professional portable flash with 200Ws power. Includes battery and modifiers.',
    category: 'Lighting',
    pricePerDay: 600,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['flash', 'lighting', 'portable', 'studio', 'outdoor'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod6',
    shopId: 'shop2',
    title: 'Manfrotto Tripod (Pro)',
    description: 'Heavy-duty carbon fiber tripod with ball head. Supports up to 8kg.',
    category: 'Accessories',
    pricePerDay: 250,
    city: 'Mumbai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['tripod', 'support', 'carbon-fiber', 'stable'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod7',
    shopId: 'shop1',
    title: 'Canon RF 70-200mm f/2.8 L',
    description: 'Professional telephoto zoom lens for Canon RF mount. Perfect for sports and wildlife.',
    category: 'Lenses',
    pricePerDay: 2200,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'telephoto', 'zoom', 'sports', 'wildlife'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod8',
    shopId: 'shop2',
    title: 'Sony FE 85mm f/1.4 GM',
    description: 'Premium portrait lens with exceptional bokeh. Perfect for professional portraits.',
    category: 'Lenses',
    pricePerDay: 1800,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['sony', 'portrait', 'prime', 'bokeh', 'premium'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod9',
    shopId: 'shop3',
    title: 'Nikon Z 50mm f/1.8 S',
    description: 'Sharp prime lens for Nikon Z mount. Great for portraits and general photography.',
    category: 'Lenses',
    pricePerDay: 1200,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['nikon', 'prime', 'portrait', 'sharp'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod10',
    shopId: 'shop4',
    title: 'Canon RF 24-105mm f/4 L',
    description: 'Versatile zoom lens covering wide to telephoto. Ideal for travel and events.',
    category: 'Lenses',
    pricePerDay: 1500,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'zoom', 'versatile', 'travel', 'events'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod11',
    shopId: 'shop1',
    title: 'Profoto B10 Plus Flash',
    description: 'Professional studio flash with 500Ws power. Includes wireless trigger.',
    category: 'Lighting',
    pricePerDay: 1200,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['flash', 'studio', 'professional', 'wireless'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod12',
    shopId: 'shop2',
    title: 'LED Video Light Panel',
    description: 'Bi-color LED panel with dimmer. Perfect for video and photography.',
    category: 'Lighting',
    pricePerDay: 400,
    city: 'Mumbai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['led', 'video', 'continuous', 'bi-color'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod13',
    shopId: 'shop3',
    title: 'DJI Ronin-S Gimbal',
    description: '3-axis camera stabilizer for smooth video. Supports cameras up to 4.5kg.',
    category: 'Accessories',
    pricePerDay: 800,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['gimbal', 'stabilizer', 'video', 'smooth'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod14',
    shopId: 'shop4',
    title: 'Canon EOS 5D Mark IV',
    description: 'Professional DSLR camera body. Perfect for studio and commercial work.',
    category: 'Cameras',
    pricePerDay: 2800,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'dslr', 'full-frame', 'professional'],
    available: true,
    instantAvailability: false,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod15',
    shopId: 'shop1',
    title: 'Sony A7S III',
    description: 'Low-light video specialist camera. Excellent for filmmaking and events.',
    category: 'Cameras',
    pricePerDay: 4000,
    city: 'Bengaluru',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['sony', 'video', 'low-light', 'filmmaking'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod16',
    shopId: 'shop2',
    title: 'Nikon D850',
    description: 'High-resolution DSLR with 45MP sensor. Perfect for landscape and commercial.',
    category: 'Cameras',
    pricePerDay: 3200,
    city: 'Mumbai',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['nikon', 'dslr', 'high-resolution', 'landscape'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod17',
    shopId: 'shop3',
    title: 'Camera Rig Cage',
    description: 'Aluminum camera cage with multiple mounting points. Compatible with most cameras.',
    category: 'Accessories',
    pricePerDay: 300,
    city: 'Delhi',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['cage', 'rig', 'mounting', 'video'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod18',
    shopId: 'shop4',
    title: 'Sony FE 16-35mm f/2.8 GM',
    description: 'Ultra-wide zoom lens for landscapes and architecture. Professional grade.',
    category: 'Lenses',
    pricePerDay: 2000,
    city: 'Chennai',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['sony', 'wide-angle', 'zoom', 'landscape'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod19',
    shopId: 'shop1',
    title: 'Softbox Lighting Kit',
    description: 'Complete softbox kit with stands and bulbs. Perfect for portrait photography.',
    category: 'Lighting',
    pricePerDay: 500,
    city: 'Bengaluru',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['softbox', 'studio', 'portrait', 'kit'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod20',
    shopId: 'shop2',
    title: 'Canon RF 50mm f/1.2 L',
    description: 'Ultra-fast prime lens with exceptional low-light performance.',
    category: 'Lenses',
    pricePerDay: 2500,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'prime', 'fast', 'low-light', 'premium'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
