import { Product, Shop } from '@/types';

export const mockShops: Shop[] = [
  {
    id: 'shop1',
    name: 'Camera Rentals Bengaluru',
    email: 'contact@camerarentalsblr.in',
    phone: '+91-9876543210',
    city: 'Bengaluru',
    address: '123 MG Road, Bengaluru',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
    rating: 4.8,
    totalRatings: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop2',
    name: 'Mumbai Camera Hub',
    email: 'info@mumbaicamerahub.com',
    phone: '+91-9876543211',
    city: 'Mumbai',
    address: '456 Bandra West, Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
    rating: 4.6,
    totalRatings: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop3',
    name: 'Delhi Pro Cameras',
    email: 'hello@delhiprocameras.in',
    phone: '+91-9876543212',
    city: 'Delhi',
    address: '789 Connaught Place, Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    rating: 4.7,
    totalRatings: 110,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop4',
    name: 'Chennai Lens & Gear',
    email: 'rentals@chennailensgear.com',
    phone: '+91-9876543213',
    city: 'Chennai',
    address: '321 T Nagar, Chennai',
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=600&fit=crop',
    rating: 4.5,
    totalRatings: 78,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop5',
    name: 'Camerascan Kottayam',
    email: 'kottayam@camerascan.in',
    phone: '+91-9876543214',
    city: 'Kottayam',
    address: 'Baker Junction, Kottayam, Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=600&fit=crop',
    rating: 4.7,
    totalRatings: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop6',
    name: 'Camerascan Thiruvalla',
    email: 'thiruvalla@camerascan.in',
    phone: '+91-9876543215',
    city: 'Thiruvalla',
    address: 'Main Road, Thiruvalla, Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&h=600&fit=crop',
    rating: 4.6,
    totalRatings: 72,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop7',
    name: 'Camerascan Pala',
    email: 'pala@camerascan.in',
    phone: '+91-9876543216',
    city: 'Pala',
    address: 'Church Road, Pala, Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop',
    rating: 4.5,
    totalRatings: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'shop8',
    name: 'Camerascan Kochi',
    email: 'kochi@camerascan.in',
    phone: '+91-9876543217',
    city: 'Kochi',
    address: 'MG Road, Kochi, Kerala',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    rating: 4.8,
    totalRatings: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Using different Unsplash images for each product - cameras, lenses, lighting, accessories
// Each product has a unique image URL
export const mockProducts: Product[] = [
  // Cameras
  {
    id: 'prod1',
    shopId: 'shop1',
    title: 'Canon EOS R6 + 24-70mm',
    description: 'Professional mirrorless camera with RF 24-70mm f/2.8 L lens. Perfect for weddings, events, and commercial photography.',
    category: 'Cameras',
    pricePerDay: 3500,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'mirrorless', 'full-frame', 'professional', 'wedding'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod2',
    shopId: 'shop2',
    title: 'Sony A7 IV + 50mm',
    description: 'Latest Sony full-frame mirrorless with 50mm f/1.8 prime lens. Excellent for portraits and low-light photography.',
    category: 'Cameras',
    pricePerDay: 3200,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['sony', 'mirrorless', 'full-frame', 'portrait', 'low-light'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod3',
    shopId: 'shop3',
    title: 'Nikon Z6 II + 24-70',
    description: 'Professional Nikon mirrorless camera with Z 24-70mm f/4 lens. Great for video and photography.',
    category: 'Cameras',
    pricePerDay: 3000,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['nikon', 'mirrorless', 'full-frame', 'video', 'hybrid'],
    available: true,
    instantAvailability: false,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod4',
    shopId: 'shop4',
    title: 'Fujifilm X-T4 + 18-55',
    description: 'Compact APS-C mirrorless camera with kit lens. Perfect for travel and street photography.',
    category: 'Cameras',
    pricePerDay: 1800,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['fujifilm', 'aps-c', 'travel', 'street', 'compact'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod14',
    shopId: 'shop4',
    title: 'Canon EOS 5D Mark IV',
    description: 'Professional DSLR camera body. Perfect for studio and commercial work.',
    category: 'Cameras',
    pricePerDay: 2800,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'dslr', 'full-frame', 'professional'],
    available: true,
    instantAvailability: false,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod15',
    shopId: 'shop1',
    title: 'Sony A7S III',
    description: 'Low-light video specialist camera. Excellent for filmmaking and events.',
    category: 'Cameras',
    pricePerDay: 4000,
    city: 'Bengaluru',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['sony', 'video', 'low-light', 'filmmaking'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod16',
    shopId: 'shop2',
    title: 'Nikon D850',
    description: 'High-resolution DSLR with 45MP sensor. Perfect for landscape and commercial.',
    category: 'Cameras',
    pricePerDay: 3200,
    city: 'Mumbai',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['nikon', 'dslr', 'high-resolution', 'landscape'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod21',
    shopId: 'shop5',
    title: 'Canon EOS R5',
    description: 'High-resolution mirrorless camera with 45MP sensor. Perfect for professional photography.',
    category: 'Cameras',
    pricePerDay: 4500,
    city: 'Kottayam',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'mirrorless', 'high-resolution', 'professional'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod22',
    shopId: 'shop6',
    title: 'Sony A7R V',
    description: 'Ultra-high resolution mirrorless camera with 61MP sensor. Perfect for commercial and landscape work.',
    category: 'Cameras',
    pricePerDay: 5000,
    city: 'Thiruvalla',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['sony', 'mirrorless', 'ultra-high-res', 'commercial'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod23',
    shopId: 'shop7',
    title: 'Nikon Z9',
    description: 'Flagship mirrorless camera with 45MP sensor. Professional sports and wildlife photography.',
    category: 'Cameras',
    pricePerDay: 5500,
    city: 'Pala',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['nikon', 'mirrorless', 'flagship', 'sports', 'wildlife'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod24',
    shopId: 'shop8',
    title: 'Panasonic Lumix S5 II',
    description: 'Professional full-frame mirrorless camera. Excellent for video and photography.',
    category: 'Cameras',
    pricePerDay: 2800,
    city: 'Kochi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['panasonic', 'mirrorless', 'full-frame', 'video'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Lenses
  {
    id: 'prod7',
    shopId: 'shop1',
    title: 'Canon RF 70-200mm f/2.8 L',
    description: 'Professional telephoto zoom lens for Canon RF mount. Perfect for sports and wildlife.',
    category: 'Lenses',
    pricePerDay: 2200,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'telephoto', 'zoom', 'sports', 'wildlife'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod8',
    shopId: 'shop2',
    title: 'Sony FE 85mm f/1.4 GM',
    description: 'Premium portrait lens with exceptional bokeh. Perfect for professional portraits.',
    category: 'Lenses',
    pricePerDay: 1800,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['sony', 'portrait', 'prime', 'bokeh', 'premium'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod9',
    shopId: 'shop3',
    title: 'Nikon Z 50mm f/1.8 S',
    description: 'Sharp prime lens for Nikon Z mount. Great for portraits and general photography.',
    category: 'Lenses',
    pricePerDay: 1200,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['nikon', 'prime', 'portrait', 'sharp'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod10',
    shopId: 'shop4',
    title: 'Canon RF 24-105mm f/4 L',
    description: 'Versatile zoom lens covering wide to telephoto. Ideal for travel and events.',
    category: 'Lenses',
    pricePerDay: 1500,
    city: 'Chennai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['canon', 'zoom', 'versatile', 'travel', 'events'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod18',
    shopId: 'shop4',
    title: 'Sony FE 16-35mm f/2.8 GM',
    description: 'Ultra-wide zoom lens for landscapes and architecture. Professional grade.',
    category: 'Lenses',
    pricePerDay: 2000,
    city: 'Chennai',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['sony', 'wide-angle', 'zoom', 'landscape'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod20',
    shopId: 'shop2',
    title: 'Canon RF 50mm f/1.2 L',
    description: 'Ultra-fast prime lens with exceptional low-light performance.',
    category: 'Lenses',
    pricePerDay: 2500,
    city: 'Mumbai',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['canon', 'prime', 'fast', 'low-light', 'premium'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod25',
    shopId: 'shop5',
    title: 'Canon RF 100-500mm f/4.5-7.1 L',
    description: 'Super telephoto zoom lens. Perfect for wildlife and sports photography.',
    category: 'Lenses',
    pricePerDay: 3000,
    city: 'Kottayam',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['canon', 'super-telephoto', 'wildlife', 'sports'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod26',
    shopId: 'shop6',
    title: 'Sony FE 24-70mm f/2.8 GM',
    description: 'Professional standard zoom lens. Versatile for all types of photography.',
    category: 'Lenses',
    pricePerDay: 2400,
    city: 'Thiruvalla',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['sony', 'standard-zoom', 'professional', 'versatile'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod27',
    shopId: 'shop7',
    title: 'Nikon Z 24-70mm f/2.8 S',
    description: 'Professional standard zoom lens for Nikon Z mount. Sharp and versatile.',
    category: 'Lenses',
    pricePerDay: 2300,
    city: 'Pala',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['nikon', 'standard-zoom', 'professional', 'sharp'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod28',
    shopId: 'shop8',
    title: 'Canon RF 35mm f/1.8 Macro',
    description: 'Wide-angle prime lens with macro capability. Perfect for close-up and street photography.',
    category: 'Lenses',
    pricePerDay: 1400,
    city: 'Kochi',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['canon', 'wide-angle', 'prime', 'macro', 'street'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Lighting
  {
    id: 'prod5',
    shopId: 'shop1',
    title: 'Godox AD200 Pro Flash',
    description: 'Professional portable flash with 200Ws power. Includes battery and modifiers.',
    category: 'Lighting',
    pricePerDay: 600,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['flash', 'lighting', 'portable', 'studio', 'outdoor'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod11',
    shopId: 'shop1',
    title: 'Profoto B10 Plus Flash',
    description: 'Professional studio flash with 500Ws power. Includes wireless trigger.',
    category: 'Lighting',
    pricePerDay: 1200,
    city: 'Bengaluru',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['flash', 'studio', 'professional', 'wireless'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod12',
    shopId: 'shop2',
    title: 'LED Video Light Panel',
    description: 'Bi-color LED panel with dimmer. Perfect for video and photography.',
    category: 'Lighting',
    pricePerDay: 400,
    city: 'Mumbai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['led', 'video', 'continuous', 'bi-color'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod19',
    shopId: 'shop1',
    title: 'Softbox Lighting Kit',
    description: 'Complete softbox kit with stands and bulbs. Perfect for portrait photography.',
    category: 'Lighting',
    pricePerDay: 500,
    city: 'Bengaluru',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['softbox', 'studio', 'portrait', 'kit'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod29',
    shopId: 'shop5',
    title: 'Godox AD600 Pro Flash',
    description: 'Professional studio flash with 600Ws power. Perfect for large studio setups.',
    category: 'Lighting',
    pricePerDay: 1500,
    city: 'Kottayam',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['flash', 'studio', 'high-power', 'professional'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod30',
    shopId: 'shop6',
    title: 'Ring Light LED (18 inch)',
    description: 'Large ring light perfect for portrait and beauty photography. Adjustable brightness and color temperature.',
    category: 'Lighting',
    pricePerDay: 350,
    city: 'Thiruvalla',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['ring-light', 'led', 'portrait', 'beauty'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod31',
    shopId: 'shop7',
    title: 'Elgato Key Light Air',
    description: 'Professional LED light panel with app control. Perfect for video content creation.',
    category: 'Lighting',
    pricePerDay: 450,
    city: 'Pala',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['led', 'video', 'content-creation', 'app-controlled'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod32',
    shopId: 'shop8',
    title: 'Aputure 300D II Light',
    description: 'Professional LED light with high output. Perfect for filmmaking and commercial work.',
    category: 'Lighting',
    pricePerDay: 1800,
    city: 'Kochi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['led', 'filmmaking', 'high-output', 'professional'],
    available: true,
    instantAvailability: false,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Accessories
  {
    id: 'prod6',
    shopId: 'shop2',
    title: 'Manfrotto Tripod (Pro)',
    description: 'Heavy-duty carbon fiber tripod with ball head. Supports up to 8kg.',
    category: 'Accessories',
    pricePerDay: 250,
    city: 'Mumbai',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['tripod', 'support', 'carbon-fiber', 'stable'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod13',
    shopId: 'shop3',
    title: 'DJI Ronin-S Gimbal',
    description: '3-axis camera stabilizer for smooth video. Supports cameras up to 4.5kg.',
    category: 'Accessories',
    pricePerDay: 800,
    city: 'Delhi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['gimbal', 'stabilizer', 'video', 'smooth'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod17',
    shopId: 'shop3',
    title: 'Camera Rig Cage',
    description: 'Aluminum camera cage with multiple mounting points. Compatible with most cameras.',
    category: 'Accessories',
    pricePerDay: 300,
    city: 'Delhi',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['cage', 'rig', 'mounting', 'video'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod33',
    shopId: 'shop5',
    title: 'DJI RS 3 Pro Gimbal',
    description: 'Professional 3-axis gimbal with advanced stabilization. Supports heavy cameras.',
    category: 'Accessories',
    pricePerDay: 1200,
    city: 'Kottayam',
    condition: 'New',
    imageUrls: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop'],
    tags: ['gimbal', 'professional', 'stabilization', 'heavy-cameras'],
    available: true,
    instantAvailability: true,
    featured: true,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod34',
    shopId: 'shop6',
    title: 'Gitzo Carbon Fiber Tripod',
    description: 'Premium carbon fiber tripod with systematic design. Lightweight and durable.',
    category: 'Accessories',
    pricePerDay: 400,
    city: 'Thiruvalla',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=800&h=600&fit=crop'],
    tags: ['tripod', 'carbon-fiber', 'premium', 'lightweight'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod35',
    shopId: 'shop7',
    title: 'Camera Slider (60cm)',
    description: 'Smooth camera slider for cinematic video movements. Perfect for time-lapse and video.',
    category: 'Accessories',
    pricePerDay: 350,
    city: 'Pala',
    condition: 'Good',
    imageUrls: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop'],
    tags: ['slider', 'video', 'cinematic', 'time-lapse'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod36',
    shopId: 'shop8',
    title: 'External Monitor 7 inch',
    description: 'Professional 7-inch external monitor for cameras. Perfect for focusing and framing.',
    category: 'Accessories',
    pricePerDay: 500,
    city: 'Kochi',
    condition: 'Excellent',
    imageUrls: ['https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop'],
    tags: ['monitor', 'external', 'focusing', 'video'],
    available: true,
    instantAvailability: true,
    featured: false,
    views: 0,
    contactClicks: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
